In [2]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

In [175]:
import pandas as pd

In [176]:
messages = pd.read_csv("../NLP/spam_collection.csv", sep='\t', names=['label','message'] )

In [177]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [178]:
messages['message'].loc[100]

"Please don't text me anymore. I have nothing else to say."

In [179]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [180]:
corpus = []

In [181]:
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z0-9]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [182]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl 3 week word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent 1 week free mem

In [183]:
#Creating Bag of words model

In [184]:
from sklearn.feature_extraction.text import CountVectorizer

In [185]:
cv = CountVectorizer(max_features = 2500, binary = True, ngram_range=(2,2))

In [186]:
X = cv.fit_transform(corpus)

In [187]:
X[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [188]:
y = pd.get_dummies(messages['label'])

In [189]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl 3 week word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent 1 week free mem

In [190]:
y = y.iloc[:,0].values 

In [191]:
y


array([1, 1, 0, ..., 1, 1, 1], dtype=uint8)

In [192]:
#train_test split

In [193]:
from sklearn.model_selection import train_test_split

In [194]:
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size = 0.20, random_state = 0)

In [195]:
X_train

<4457x2500 sparse matrix of type '<class 'numpy.int64'>'
	with 9329 stored elements in Compressed Sparse Row format>

In [196]:
from sklearn.naive_bayes import MultinomialNB


In [197]:
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [216]:
y_pred=spam_detect_model.predict(X_test)

In [217]:
from sklearn.metrics import accuracy_score,classification_report

In [218]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9721973094170404


In [219]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.81      1.00      0.89       129
           1       1.00      0.97      0.98       986

    accuracy                           0.97      1115
   macro avg       0.90      0.98      0.94      1115
weighted avg       0.98      0.97      0.97      1115



In [220]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [221]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [222]:
X[0]

<1x2500 sparse matrix of type '<class 'numpy.int64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [223]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [224]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [225]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [226]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [239]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  'receivea',
 

[('defeat', 0.8740767240524292),
 ('playing', 0.8731620907783508),
 ('idk', 0.8731566071510315),
 ('decide', 0.8716520071029663),
 ('cooking', 0.8700541257858276),
 ('sam', 0.8696379065513611),
 ('custcare', 0.8695437908172607),
 ('hotel', 0.8693437576293945),
 ('hug', 0.8675720691680908),
 ('sol', 0.8668372631072998)]

In [306]:
import gensim
import numpy as np
model=gensim.models.Word2Vec(words,window=5,min_count=2)

In [309]:
len(wv.index_to_key)

3000000

In [308]:
model.epochs

5

In [280]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    for word in doc:
        if word in model.wv.index_to_key:
             c= model.wv[word]
             break
        
    return c    
#     return ([model.wv[word] break for word in doc if word in model.wv.index_to_key],axis=0)
               
        
    

In [231]:
from tqdm import tqdm,trange

In [287]:
# apply for the entire sentences
X=[]
for i in range(len(words)):
     X.append(avg_word2vec(words[i]))
     break


In [290]:
X[0]

array([-0.27511686,  0.73908204,  0.3735044 ,  0.05617478,  0.07499446,
       -0.8148562 ,  0.22860362,  1.2987077 , -0.43017358, -0.38427353,
       -0.40630022, -0.8546474 , -0.01604156,  0.24015743,  0.18729886,
       -0.7145884 ,  0.04635989, -0.85393333, -0.04594241, -1.1187639 ,
        0.17412633,  0.3792753 ,  0.25571212, -0.32338765, -0.2830423 ,
        0.0710999 , -0.5205896 , -0.3679733 , -0.54745495,  0.13769603,
        0.7446404 ,  0.13222325,  0.37282005, -0.595978  , -0.29281792,
        0.66802394,  0.09038466, -0.48528108, -0.43328887, -0.9531    ,
        0.15960903, -0.58898544, -0.23419306,  0.11392518,  0.6195935 ,
       -0.33821577, -0.44653398,  0.08864968,  0.3637539 ,  0.5935663 ,
        0.42515644, -0.7175169 , -0.1396715 , -0.03980792, -0.33567178,
        0.52289766,  0.4395167 , -0.10158528, -0.6879229 ,  0.15401508,
        0.27065304,  0.30640718, -0.31028917, -0.00469156, -0.6641334 ,
        0.4052739 ,  0.2167149 ,  0.48556307, -0.7137137 ,  0.81

In [258]:
X

[array([-1.07059948e-01,  2.94978082e-01,  1.47339076e-01,  2.46902555e-02,
         3.61974724e-02, -3.25634420e-01,  8.92647505e-02,  5.18412530e-01,
        -1.66421875e-01, -1.52248904e-01, -1.57174513e-01, -3.43220264e-01,
        -6.50857063e-03,  9.52015743e-02,  7.81037956e-02, -2.82928705e-01,
         2.03152578e-02, -3.38443041e-01, -1.66563056e-02, -4.46213871e-01,
         7.16085136e-02,  1.52041361e-01,  9.86713246e-02, -1.27444178e-01,
        -1.07607275e-01,  2.78969612e-02, -2.09859833e-01, -1.43757597e-01,
        -2.21749887e-01,  5.08459248e-02,  2.94062048e-01,  5.78529537e-02,
         1.51107714e-01, -2.35436991e-01, -1.19728237e-01,  2.63218641e-01,
         3.38875093e-02, -1.96652368e-01, -1.75697684e-01, -3.77341002e-01,
         6.25148490e-02, -2.34334514e-01, -9.20413733e-02,  4.72279824e-02,
         2.47149229e-01, -1.33464977e-01, -1.78886130e-01,  3.17936204e-02,
         1.43085465e-01,  2.39306808e-01,  1.71020329e-01, -2.82804966e-01,
        -5.5

In [259]:
type(X)

list

In [260]:
X_new = np.array(X)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5564,) + inhomogeneous part.

In [267]:
len(wv.index_to_key)

3000000