In [1]:
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.datasets import load_iris

In [2]:
data = load_iris()

In [3]:
data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
arr = np.arange(0,10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr = np.arange(1000000)

In [7]:
li = [1,2,3]

In [8]:
%time for _ in range(10):{item * 3 for item in li }
    

CPU times: total: 0 ns
Wall time: 0 ns


In [9]:
%time for _ in range(10):arr*3

CPU times: total: 0 ns
Wall time: 10.3 ms


In [30]:
arr1 = np.array([[12,2,3],[4,5,6]], dtype='int64')

In [11]:
arr1

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [12]:
3*li

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [13]:
arr1.shape

(2, 3)

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr1

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [16]:
type(arr1)

numpy.ndarray

In [17]:
np.zeros(4)

array([0., 0., 0., 0.])

In [18]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
arr1.dtype="int64"

ValueError: When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.

In [31]:
arr1**arr1

array([[8916100448256,             4,            27],
       [          256,          3125,         46656]], dtype=int64)

## Slicing is just a view of a portion of an actual array

In [68]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]]) 

In [43]:
array2 = np.array([2,3,4,5])

In [44]:
arr = array2[0:2].copy()

In [45]:
arr[1] = 6

In [46]:
arr

array([2, 6])

In [47]:
array2

array([2, 3, 4, 5])

In [48]:
array1[0]

array([1, 2, 3])

In [50]:
array1[1]

array([4, 5, 6])

In [52]:
array1[0][0:2]

array([1, 2])

In [61]:
array1.sum(axis=1)

array([ 6, 15])

In [63]:
array1.max(axis=0)

array([4, 5, 6])

In [70]:
b =  np.array([[7,8,9],[2,4,7]]) 

In [91]:
b

array([[7, 8, 9],
       [2, 4, 7]])

In [83]:
np.dot(a,b.transpose())

array([[ 50,  31],
       [122,  70],
       [194, 109]])

In [84]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [86]:
np.cross(a,b.transpose())

array([[ -6,  21, -12],
       [-24,  48, -24],
       [-63,  81, -23]])

In [87]:
np.sort(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
np.sort(b)

array([[7, 8, 9],
       [2, 4, 7]])

In [89]:
np.sort(a, axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
np.sort(b,axis=0, kind='quicksort')

array([[2, 4, 7],
       [7, 8, 9]])

In [96]:
c = np.array([2,2,1,3,4,6,6,78,3,4332,234,3,5,6,7,8,5,3,3,5,6,7,7,3])

In [97]:
len(c)

24

In [98]:
c.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

In [143]:
d = c.reshape(6,4)

In [144]:
d

array([[   2,    2,    1,    3],
       [   4,    6,    6,   78],
       [   3, 4332,  234,    3],
       [   5,    6,    7,    8],
       [   5,    3,    3,    5],
       [   6,    7,    7,    3]])

In [100]:
np.argsort(c)

array([ 2,  0,  1, 18, 17,  8, 11, 23,  3,  4, 12, 16, 19,  5, 20, 13,  6,
       21, 22, 14, 15,  7, 10,  9], dtype=int64)

In [101]:
np.argmin(c)

2

In [103]:
np.argmax(c)

9

In [110]:
np.argsort(d,axis=1)

array([[2, 0, 1, 3],
       [0, 1, 2, 3],
       [0, 3, 2, 1],
       [0, 1, 2, 3],
       [1, 2, 0, 3],
       [3, 0, 1, 2]], dtype=int64)

In [111]:
j = np.expand_dims(d, axis=0)

In [112]:
j

array([[[   2,    2,    1,    3],
        [   4,    6,    6,   78],
        [   3, 4332,  234,    3],
        [   5,    6,    7,    8],
        [   5,    3,    3,    5],
        [   6,    7,    7,    3]]])

In [113]:
j.shape

(1, 6, 4)

In [122]:
h = d[np.newaxis]

In [123]:
h

array([[[   2,    2,    1,    3],
        [   4,    6,    6,   78],
        [   3, 4332,  234,    3],
        [   5,    6,    7,    8],
        [   5,    3,    3,    5],
        [   6,    7,    7,    3]]])

In [155]:
w = np.expand_dims(d, axis=1)

In [156]:
w.shape

(6, 1, 4)

In [157]:
d.shape

(6, 4)

In [158]:
w

array([[[   2,    2,    1,    3]],

       [[   4,    6,    6,   78]],

       [[   3, 4332,  234,    3]],

       [[   5,    6,    7,    8]],

       [[   5,    3,    3,    5]],

       [[   6,    7,    7,    3]]])

In [159]:
d

array([[   2,    2,    1,    3],
       [   4,    6,    6,   78],
       [   3, 4332,  234,    3],
       [   5,    6,    7,    8],
       [   5,    3,    3,    5],
       [   6,    7,    7,    3]])

In [160]:
d.shape

(6, 4)

In [161]:
w.shape

(6, 1, 4)

In [147]:
arr1 = np.arange(15).reshape(3,5)

In [148]:
arr1.shape

(3, 5)

In [149]:
arr1.sort()

In [150]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [153]:
s = arr1.sum(axis=0)

In [167]:
s

array([15, 18, 21, 24, 27])

In [172]:
arr1[:, ..., np.newaxis].shape

(3, 5, 1)